server:
  port: 8090

logging:
  level:
    root:
      ${LOG_LEVEL}

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: frontend
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/home**,/favicon.ico/,/static/**,
        - id: waitlist-service
          uri: ${WAITLIST_SERVICE_URL}
          predicates:
            - Path=/waitlist
        - id: floor-plan-service
          uri: ${FLOOR_PLAN_SERVICE_URL}
          predicates:
            - Path=/floorMap

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: auth-server
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}