server:
  port: 8090

logging:
  level:
    root:
      INFO

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: frontend
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/home/,/favicon.ico/,/static/**,

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: auth-server
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}