server:
  port: 8090

logging:
  level:
    root:
      ${LOG_LEVEL}

spring:
  cloud:
    gateway:
      routes:
        - id: frontend
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/static/**, /icons/**, /ui/**

        - id: waitlist-service
          uri: ${WAITLIST_SERVICE_URL}
          predicates:
            - Path=/waitlist
          filters:
            - TokenRelay=

        - id: reservation-service
          uri: ${RESERVATION_SERVICE_URL}
          predicates:
            - Path=/reservation,/available
          filters:
            - TokenRelay=

        - id: restaurant-service
          uri: ${RESTAURANT_SERVICE_URL}
          predicates:
            - Path=/floorMaps, /floorMap, /floorMapItem, /restaurant**, /servicetype, /restaurants**,/restaurant/**
          filters:
            - TokenRelay=

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/user
          filters:
            - TokenRelay=

        - id: catch-all-frontend
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/**
          filters:
            - RedirectTo=302, /ui

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: auth-server
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}