server:
  port: 8090

logging:
  level:
    root:
      ${LOG_LEVEL}



  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: auth-server
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}