version: '2'

services:
  auth:
    image: 'ghcr.io/jakegergen714/auth:latest'
    build:
      context: .
    container_name: auth
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - REDIRECT_URI=http://192.168.1.241:8090/login/oauth2/code/gateway
      - LOG_LEVEL=DEBUG
    ports:
      - "9000:9000"

  gateway:
    image: 'ghcr.io/jakegergen714/basic-cloud-gateway:latest'
    build:
      context: .
    environment:
      - REDIRECT_URI=http://192.168.1.241:8090/login/oauth2/code/{registrationId}
      - ISSUER_URI=http://192.168.1.241:9000
      - FRONTEND_URL=http://192.168.1.241:3000/
      - WAITLIST_SERVICE_URL=http://192.168.1.241:8080/waitlist
      - FLOOR_PLAN_SERVICE_URL=http://192.168.1.241:8085/floorMap
      - LOG_LEVEL=DEBUG
    container_name: gateway
    depends_on:
      - auth
    ports:
      - "8090:8090"

  waitlist:
    image: 'ghcr.io/jakegergen714/waitlist:latest'
    build:
      context: .
    container_name: waitlist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ISSUER_URI=http://192.168.1.241:9000
      - LOG_LEVEL=DEBUG
    ports:
      - "8080:8080"

  floor-map-service:
    image: 'ghcr.io/jakegergen714/floor-map-service:latest'
    build:
      context: .
    container_name: floor-map-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ISSUER_URI=http://192.168.1.241:9000
      - LOG_LEVEL=DEBUG
      - PORT=8085
    ports:
      - "8085:8085"

  frontend-api:
    image: 'ghcr.io/jakegergen714/frontend-api:latest'
    depends_on:
      - db
    build:
      context: .
    container_name: frontend-api
    ports:
      - "8082:8082"
    environment:
      - URL_AUTH_SERVICE=http://192.168.1.241:8081
      - URL_WAITLIST_SERVICE=http://192.168.1.241:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: 'ghcr.io/jakegergen714/sms-front-end:latest'
    build:
      context: .
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://192.168.1.241:8082
    ports:
      - "3000:3000"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"