version: '2'

services:
  auth:
    image: 'ghcr.io/jakegergen714/auth:latest'
    build:
      context: .
    container_name: auth
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - "8081:8081"
  
  waitlist:
    image: 'ghcr.io/jakegergen714/waitlist:latest'
    build:
      context: .
    container_name: waitlist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - "8080:8080"
  
  frontend-api:
    image: 'ghcr.io/jakegergen714/frontend-api:latest'
    build:
      context: .
    container_name: frontend-api
    ports:
    - "8082:8082"
    environment:
      - URL_AUTH_SERVICE=http://auth:8081
      - URL_WAITLIST_SERVICE=http://waitlist:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: 'ghcr.io/jakegergen714/sms-front-end:latest'
    build:
      context: .
    container_name: frontend
    environment:
      - API_URL=http://frontend-api:8082
    ports:
    - "3000:3000"

          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
    - "5432:5432"