name: Maven Package and Docker Build

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      
      - name: Build with Maven
        working-directory: ./auth/
        run: mvn -B package --file pom.xml
      
      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
        working-directory: ./auth/
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }} ./auth
          docker push ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}
