# @format

name: Maven Package and Docker Build

on: push

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with Auth
           working-directory: ./auth/
           run: mvn -B package --file pom.xml

         - name: Build with Wait List
           working-directory: ./waitlist-service/
           run: mvn -B package --file pom.xml

         - name: Build with Front End API
           working-directory: ./frontend-api/
           run: mvn -B package --file pom.xml

         - name: Publish Auth
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./auth/
           run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
          
        - name: Publish Waitlist Service
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
          working-directory: ./waitlist-service/
          run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        
        - name: Publish Frontend API
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
          working-directory: ./frontend-api/
          run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/my-app:0a997b8af1bc87d1656b352051dfe100a9dbae0f ./auth
              docker push ghcr.io/jakegergen714/my-app:0a997b8af1bc87d1656b352051dfe100a9dbae0f
