# @format

name: Maven Package and Docker Build data-core-lib

on:
   push:
      paths:
         - "data-core-lib/**"
         - ".github/publish-data-core-lib.yml"
   pull_request:
      paths:
         - "data-core-lib/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with Wait List
           working-directory: ./data-core-lib/
           run: mvn -B package --file pom.xml

         - name: Publish data-core-lib Service
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./data-core-lib/
           run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}
