# @format

name: Maven Package and Docker Build Auth

on:
   push:
      paths:
         - "auth/**"
         - ".github/**"
   pull_request:
      paths:
         - "auth/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v4

         - name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with Auth
           working-directory: ./auth/
           run: mvn -B package --file pom.xml

         - name: Publish Auth
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./auth/
           run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push Auth Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/auth:latest ./auth
              docker push ghcr.io/jakegergen714/auth:latest
