# @format

name: Gradle Package and Docker Build basic-cloud-gateway

on:
   push:
      paths:
         - "basic-cloud-gateway/**"
         - ".github/**"
   pull_request:
      paths:
         - "basic-cloud-gateway/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with Gradle
           working-directory: ./basic-cloud-gateway/
           # Use the Gradle wrapper script to build the project. Assumes a task named 'build'.
           run: ./gradlew build

         # If you need to publish artifacts to a repository, you might need a custom task in your gradle build script.
         # This example assumes you have configured a publishing task in your gradle script.
         - name: Publish Cloud Gateway
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./basic-cloud-gateway/
           run: ./gradlew publish -PgithubToken=${{ secrets.ACCESS_TOKEN }}

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push basic-cloud-gateway Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/basic-cloud-gateway:$GITHUB_SHA -t ghcr.io/jakegergen714/basic-cloud-gateway:latest ./basic-cloud-gateway
              docker push ghcr.io/jakegergen714/basic-cloud-gateway:$GITHUB_SHA
              docker push ghcr.io/jakegergen714/basic-cloud-gateway:latest
