# @format

name: Maven Package and Docker Build basic-cloud-gateway

on:
   push:
      paths:
         - "basic-cloud-gateway/**"
         - ".github/**"
   pull_request:
      paths:
         - "basic-cloud-gateway/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with basic-cloud-gateway
           working-directory: ./basic-cloud-gateway/
           run: gradle build

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push basic-cloud-gateway Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/basic-cloud-gateway:$GITHUB_SHA -t ghcr.io/jakegergen714/basic-cloud-gateway:latest ./basic-cloud-gateway
              docker push ghcr.io/jakegergen714/basic-cloud-gateway:$GITHUB_SHA
              docker push ghcr.io/jakegergen714/basic-cloud-gateway:latest
