# @format

name: Maven Package and Docker Build Front End API

on:
   push:
      paths:
         - "frontend-api/**"
         - ".github/**"
   pull_request:
      paths:
         - "frontend-api/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with Front End API
           working-directory: ./frontend-api/
           run: mvn -B package --file pom.xml

         - name: Publish Frontend API
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./frontend-api/
           run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push Waitlist Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/frontend-api:latest ./frontend-api
              docker push ghcr.io/jakegergen714/frontend-api:latest
