# @format

name: Maven Package and Docker Build restaurant

on:
   push:
      paths:
         - "restaurant-service/**"
         - ".github/workflows/publish-restaurant-service.yml"
   pull_request:
      paths:
         - "restaurant-service/**"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v4

         - name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
              java-version: "17"
              distribution: "temurin"
              server-id: github
              settings-path: ${{ github.workspace }}

         - name: Build with restaurant Service
           working-directory: ./restaurant-service/
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file pom.xml

         - name: Cache local Maven repository
            uses: actions/cache@v3
            with:
               path: ~/.m2/repository
               key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
               restore-keys: |
                  ${{ runner.os }}-maven-

         - name: Publish restaurant Service
           env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Assuming you're using the GitHub provided token
           working-directory: ./restaurant-service/
           run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.ACCESS_TOKEN }}

         - name: Build and push restaurant_service Docker image
           run: |
              docker build -t ghcr.io/jakegergen714/restaurant_service:latest ./restaurant-service
              docker push ghcr.io/jakegergen714/restaurant_service:latest
